### ISSUE TITLE
'Permission denied' error

### ISSUE THREAD

**Issue by icycandy** [lebedov/scikit-cuda#129]
I installed scikit-cuda 0.5.0 with root user, with command `python setup.py install`
CentOS 7.0-1406, kernel 3.10.0-1

```python
[candy@f22]$ python
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import skcuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/scikit_cuda-0.5.0-py2.7.egg/skcuda/__init__.py", line 4, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3084, in <module>
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3070, in _call_aside
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3109, in _initialize_master_working_set
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 965, in subscribe
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3109, in <lambda>
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2626, in activate
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2616, in _get_metadata
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1625, in get_metadata_lines
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1617, in get_metadata
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1728, in _get
    
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/scikit_cuda-0.5.0-py2.7.egg/EGG-INFO/namespace_packages.txt'
>>> 
```

**Comment by lebedov** [comment]
The root user umask on your system is probably set to not make newly created/installed files world readable by default. You will have to make the installed files world readable manually.

As an aside, I personally prefer not to install Python software as root in the system directories if it hasn't been explicitly packaged for whatever Linux distribution one is using; you may wish to try using [virtualenv](https://virtualenv.pypa.io/) or [conda](https://virtualenv.pypa.io/) to create a local Python environment in your non-root user's home directory.

**Comment by icycandy** [comment]
After add read permission, now normal user can successfully import skcuda.
```bash
chmod +r /usr/lib/python2.7/site-packages/scikit_cuda-0.5.0-py2.7.egg/EGG-INFO/*
```

BTW. How to make the installed files world readable?

**Comment by icycandy** [comment]
I found that it may be the file permission caused this issue. I download [scikit-cuda 0.5.0](https://pypi.python.org/pypi/scikit-cuda/0.5.0) and unzipped it. The files in `scikit_cuda.egg-info` are readable only by the user who installed it.

```bash
[candy@f22 scikit-cuda-0.5.0]$ ll scikit_cuda.egg-info/
total 28
-rw-------. 1 candy candy    1 Jul 14 23:03 dependency_links.txt
-rw-------. 1 candy candy   15 Jul 14 23:03 namespace_packages.txt
-rw-------. 1 candy candy   47 Jul 14 23:03 pbr.json
-rw-------. 1 candy candy  756 Jul 14 23:03 PKG-INFO
-rw-------. 1 candy candy  117 Jul 14 23:03 requires.txt
-rw-------. 1 candy candy 1839 Jul 14 23:03 SOURCES.txt
-rw-------. 1 candy candy   21 Jul 14 23:03 top_level.txt
```

For a comparision, here is egg info of [chainer 1.1.1](https://pypi.python.org/pypi/chainer/1.1.1)
```bash
[candy@f22 chainer-1.1.1]$ ll chainer.egg-info/
total 24
-rw-rw-r--. 1 candy candy    1 Jul 22 15:00 dependency_links.txt
-rw-rw-r--. 1 candy candy   47 Jul 22 15:00 pbr.json
-rw-rw-r--. 1 candy candy  240 Jul 22 15:00 PKG-INFO
-rw-rw-r--. 1 candy candy   31 Jul 22 15:00 requires.txt
-rw-rw-r--. 1 candy candy 2123 Jul 22 15:00 SOURCES.txt
-rw-rw-r--. 1 candy candy    8 Jul 22 15:00 top_level.txt
```

**Comment by lebedov** [comment]
You can use `chmod a+r /path/to/file` to make a file world readable. `chmod -R a+r /path/to/directory` will recursively update the permissions of the directory and all of its subdirectories and files.

Since `python setup.py install` copies files into the destination path, the file permissions of the contents of a zip or tar file shouldn't affect those of the installed files. Take a look at the man page for `umask`

**Comment by icycandy** [comment]
Since `python setup.py install` copies files, so the file permissions of the source and destination files should be identical.

I installed `scikit-cuda 0.5.0` on a new machine, before install I add read permission to files in `scikit_cuda.egg-info`. You can see after install by root user, these files are readable by normal user.

```bash
[candy@f22 scikit-cuda-0.5.0]$ ll scikit_cuda.egg-info/
total 28
-rw-------. 1 candy candy    1 Jul 14 23:03 dependency_links.txt
-rw-------. 1 candy candy   15 Jul 14 23:03 namespace_packages.txt
-rw-------. 1 candy candy   47 Jul 14 23:03 pbr.json
-rw-------. 1 candy candy  756 Jul 14 23:03 PKG-INFO
-rw-------. 1 candy candy  117 Jul 14 23:03 requires.txt
-rw-------. 1 candy candy 1839 Jul 14 23:03 SOURCES.txt
-rw-------. 1 candy candy   21 Jul 14 23:03 top_level.txt

[candy@f22 scikit-cuda-0.5.0]$ chmod +r scikit_cuda.egg-info/*

[candy@f22 scikit-cuda-0.5.0]$ ll scikit_cuda.egg-info/
total 28
-rw-r--r--. 1 candy candy    1 Jul 30 10:09 dependency_links.txt
-rw-r--r--. 1 candy candy   15 Jul 30 10:09 namespace_packages.txt
-rw-r--r--. 1 candy candy   47 Jul 14 23:03 pbr.json
-rw-r--r--. 1 candy candy  756 Jul 30 10:09 PKG-INFO
-rw-r--r--. 1 candy candy  117 Jul 30 10:09 requires.txt
-rw-r--r--. 1 candy candy 1849 Jul 30 10:09 SOURCES.txt
-rw-r--r--. 1 candy candy   21 Jul 30 10:09 top_level.txt

[candy@f22 scikit-cuda-0.5.0]$ su
Password: 

[root@f22 scikit-cuda-0.5.0]$ python setup.py install
install messages .....

[root@f22 scikit-cuda-0.5.0]$ exit
exit

[candy@f22 scikit-cuda-0.5.0]$ ll /usr/lib/python2.7/site-packages/scikit_cuda-0.5.0-py2.7.egg/EGG-INFO/
total 32
-rw-r--r--. 1 root root    1 Jul 30 10:09 dependency_links.txt
-rw-r--r--. 1 root root   15 Jul 30 10:09 namespace_packages.txt
-rw-r--r--. 1 root root    1 Jul 30 10:09 not-zip-safe
-rw-r--r--. 1 root root   47 Jul 30 10:09 pbr.json
-rw-r--r--. 1 root root  756 Jul 30 10:09 PKG-INFO
-rw-r--r--. 1 root root  117 Jul 30 10:09 requires.txt
-rw-r--r--. 1 root root 1849 Jul 30 10:09 SOURCES.txt
-rw-r--r--. 1 root root   21 Jul 30 10:09 top_level.txt

```

**Comment by lebedov** [comment]
On my Ubuntu system, the umask setting takes precedence regardless of the original files' permissions (even as root). Don't know whether Centos has some special settings.
