### ISSUE TITLE
setup.py issue with Windows/Anaconda

### ISSUE THREAD

**Issue by allthedata** [lebedov/scikit-cuda#130]
I'm running Windows and the Anaconda distribution, so I'm not sure if this applies on other platforms. After using pip to install `scikit-cuda` from either pypi or from the github repository, `setuptools` can no longer be imported. This also breaks quite a few things including the ipython qtconsole.

I found that this is due to the scikit-cuda install misplacing the `C:\Users\User\Anaconda3\scikits\__init__.py` and `C:\Users\User\Anaconda3\skcuda\__init__.py` files, which should instead be located at `C:\Users\User\Anaconda3\Lib\site-packages\scikits\__init__.py` and `C:\Users\User\Anaconda3\Lib\site-packages\skcuda\__init__.py`. After moving these files, everything works fine.

The error on importing setuptools is shown below.

```python
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\setuptools\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\setuptools\extension.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\setuptools\dist.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 3084, in <module>
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 3070, in _call_aside
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 3109, in _initialize_master_working_set
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 965, in subscribe
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 3109, in <lambda>
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 2628, in activate
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 2219, in declare_namespace
  File "C:\Users\User\Anaconda3\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 2186, in _handle_ns
  File ".\skcuda\__init__.py", line 10, in <module>
    from .version import __version__
  File ".\skcuda\version.py", line 2, in <module>
    __version__ = pkg_resources.require('scikit-cuda')[0].version
TypeError: 'NoneType' object is not callable
```

**Comment by lebedov** [comment]
Can you try installing the [fix-pip-install](https://github.com/lebedov/scikit-cuda/tree/fix-pip-install) branch via pip and let me know if it solves the problem?

**Comment by lebedov** [comment]
Given that the modification I made in 3f8ccc9 appeared to fix [other installation issues](https://github.com/lebedov/scikit-cuda/issues/144), I merged it and posted a new release. Feel free to reopen if you continue to encounter problems.
