### ISSUE TITLE
problems with cusolverDnSgesvd 

### ISSUE THREAD

**Issue by zevektor** [lebedov/scikit-cuda#145]
I am trying to perform SVD using cusolver-dense, using this [answer](http://stackoverflow.com/questions/29780180/getrs-function-of-cusolver-over-pycuda-doesnt-work-properly?answertab=active#tab-top) as reference

When running the code, I get this error
```
Traceback (most recent call last):
  File "/home/zan/svd.py", line 55, in <module>
    devInfo=devInfo.gpudata
  File "/home/zan/anaconda3/lib/python3.4/site-packages/skcuda/cusolver.py", line 579, in cusolverDnSgesvd
    int(devInfo))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```
This is how I set devInfo parameter
```
devInfo = gpuarray.zeros(1, dtype=np.int32)
```

and I use devInfo.gpudata as argument in cusolverDnSgesvd method. 

I can't say if I'm doing something wrong of this is a problem with the wrapper

**Comment by lebedov** [comment]
I just updated `skcuda.linalg.svd()` [to support](e58ffa2) using CUSOLVER if so desired.

**Comment by zevektor** [comment]
It still doesn't work unfortunately:
```
Traceback (most recent call last):
 File "/home/zan/test_svd.py", line 15, in <module>
    u_gpu, s_gpu, vh_gpu = culinalg.svd(a_gpu,'A','A',lib='cusolver')
  File "/home/zan/anaconda3/lib/python3.4/site-packages/skcuda/linalg.py", line 244, in svd
    int(devInfo.gpudata))
  File "/home/zan/anaconda3/lib/python3.4/site-packages/skcuda/cusolver.py", line 631, in cusolverDnDgesvd
    Lwork, int(rwork), int(devInfo))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by lebedov** [comment]
Seems like Python 3 issues - I just uploaded another tweak (3b43c03) to fix them. Can you please try it out?

**Comment by zevektor** [comment]
```
Traceback (most recent call last):
  File "/home/vektor/PycharmProjects/yancut/test_svd.py", line 16, in <module>
    u_gpu, s_gpu, vh_gpu = culinalg.svd(a_gpu=a_gpu,jobu='A',jobvt='A',lib='cusolver')
  File "/home/vektor/anaconda3/lib/python3.4/site-packages/skcuda/linalg.py", line 247, in svd
    int(devInfo.gpudata))
  File "/home/vektor/anaconda3/lib/python3.4/site-packages/skcuda/cusolver.py", line 582, in cusolverDnSgesvd
    cusolverCheckStatus(status)
  File "/home/vektor/anaconda3/lib/python3.4/site-packages/skcuda/cusolver.py", line 134, in cusolverCheckStatus
    raise CUSOLVER_EXCEPTIONS[status]
skcuda.cusolver.CUSOLVER_STATUS_INVALID_VALUE
```

**Comment by lebedov** [comment]
What are the dimensions of your matrix? CUSOLVER's SVD can only decompose matrices [with m >= n](http://docs.nvidia.com/cuda/cusolver/#cuds-lt-t-gt-gesvd) (which implies that the matrix passed to the function must have n >= m because row-ordered numpy matrices are regarded as transposed by CUSOLVER).
