### ISSUE TITLE
cublasZgemm in testing

### ISSUE THREAD

**Issue by petergthatsme** [lebedov/scikit-cuda#162]
First of all, thanks for writing this nice package!

i noticed that a test for cublasZgemm is not in the testing suite. Is this intentional? It would seem like the wrapper does exist in the code, so I'm guessing it is "officially" supported?

I seem to run into a problem using cublasZgemm, (although it could be that i'm not calling it in the right way), Basically the code:

EDIT: got rid of the assert statement in originally posted code - leftover from a different function

```
def example_cublasZgemm(handle):

    N=10
    a=(np.random.rand(N,N)+1.0j*np.random.rand(N,N)).astype(np.complex128)
    b=(np.random.rand(N,N)+1.0j*np.random.rand(N,N)).astype(np.complex128)
    c=a*b

    a_gpu = gpuarray.to_gpu(a.copy())
    b_gpu = gpuarray.to_gpu(b.copy())
    c_gpu = gpuarray.zeros_like(a_gpu)

    alpha = np.complex128(1.0)
    beta = np.complex128(0.0)
    cublas.cublasZgemm(handle, 'n', 'n', N, N, N,
                       alpha, a_gpu.gpudata, N,
                       beta, b_gpu.gpudata, N,
                       c_gpu.gpudata, N)

    c_from_gpu=c_gpu.get()

    return a,b,c,c_from_gpu

handle = cublas.cublasCreate()
a,b,c,c_from_gpu = example_cublasZgemm(handle)
cublas.cublasDestroy(handle)  

```
... leads to the following error:

```
/usr/local/lib/python2.7/dist-packages/skcuda/cublas.py:4383: ComplexWarning: Casting complex values to real discards the imaginary part
  int(A), lda, int(B), ldb,
Traceback (most recent call last):
  File "./mult.py", line 37, in <module>
    a,b,c,c_from_gpu = example_cublasZgemm(handle)
  File "./mult.py", line 30, in example_cublasZgemm
    c_from_gpu=c_gpu.get()
  File "/usr/local/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 271, in get
    _memcpy_discontig(ary, self, async=async, stream=stream)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 1190, in _memcpy_discontig
    drv.memcpy_dtoh(dst, src.gpudata)
pycuda._driver.LogicError: cuMemcpyDtoH failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
```

thanks!

**Comment by lebedov** [comment]
You are not passing the arguments to the function in the right order. Also, because numpy stores arrays in row-major format and CUBLAS assumes arrays are in column-major format, ``cublasZgemm`` will actually be computing ``dot(a.T, b.T)`` in this case.

**Comment by petergthatsme** [comment]
thanks, i don't know how i possibly missed the arguments order.. something i thought i double-checked!
