### ISSUE TITLE
SVD on GPU is MUCH slower than on CPU

### ISSUE THREAD

**Issue by hnykda** [lebedov/scikit-cuda#182]
Hey,

I have the following code:

```
    # measurement
    from timeit import timeit
    import pycuda.gpuarray as gpuarray
    import pycuda.autoinit
    import numpy as np
    from skcuda.linalg import svd
    import skcuda
    skcuda.misc.init()
    N = 6400
    Y = np.random.randn(N, N) + 1j*np.random.randn(N, N)
    X = np.asarray(Y, np.complex64)
    a_gpu = gpuarray.to_gpu(X)
         
    tm = timeit("svd(a_gpu, jobu='A', jobvt='A', lib='cusolver')", 
                    globals={'a_gpu': a_gpu, 'svd': svd}, 
                    number=1)
```

You should be able to run it if you have `skcuda`, `pycuda` and `pandas` installed. 

What I am trying to do is to compare the speed with `numpy`'s SVD version:
```
    import numpy as np
    import pandas as pd
    from timeit import timeit
    N = 10000
    X = np.random.randn(N, N).astype('float32')
    tm = timeit('svd(X, full_matrices=True)', 
                    globals={'X': X, 'svd': np.linalg.svd}, 
                    number=1)

```

but when I compare the results, it is terrible for GPU. On CPU, I compute SVD matrix about 10000 rows in 15 minutes on single CPU with numpy, while on skcuda SVD it takes about 90 minutes for matrix about 6400 rows.

Am I doing something wrong? I can see that skcuda is using the card (at least it is warming up and taking up memory on the card).

**Comment by lebedov** [comment]
You don't appear to be doing anything wrong. What version of CUDA are you using? [This](https://devtalk.nvidia.com/default/topic/830894/cusolverdncgesvd-performance-vs-mkl/) thread on NVIDIA's dev forum indicates that the performance of the initial SVD implementation in CUSOLVER was acknowledged to be less than stellar, but that in CUDA 8.0 might be a bit better. (For the record, I tried CUSOLVER 8.0, but its SVD implementation still seems considerably slower than CPU-based implementations even for matrices of size ~1000x1000.)

**Comment by hnykda** [comment]
Hey. Sorry for not posting the version in the first post:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
```

I unfortunately cannot upgrade to CUDA 8.0 (don't have a root on that computer and I think it would break a lot of current code)

**Comment by lebedov** [comment]
You also might want to try the SVD routines in MAGMA; although `linalg.svd()` doesn't currently support the use of MAGMA,  `demos/magma_svd_demo.py` shows how to call the wrapper functions.

**Comment by hnykda** [comment]
Thanks, but I don't have MAGMA. I believe it is in CUDA 8 - or am I wrong?

```
$ python demo_magma.py
Traceback (most recent call last):
  File "demo_magma.py", line 8, in <module>
    import skcuda.magma as magma
  File "/home/hnykdan1/vu/skcuda/scikit-cuda/skcuda/magma.py", line 36, in <module>
    raise OSError('%s not found' % _load_err)
OSError: libmagma.so not found
```

**Comment by lebedov** [comment]
MAGMA is a separate open source library you have to compile and install
yourself.

**Comment by hnykda** [comment]
Hey. Thanks for the answer. I was able to compile it, but since I don't have a root access, I cannot add it to my lib and include path (and haven't found a way how to link it to skcuda in some other way).

**Comment by lebedov** [comment]
Assuming you are on Linux, try adding the full path of the directory in which `libmagma.so` is installed to the LD_LIBRARY_PATH environmental variable. If that doesn't work for some reason, you can hard-code the path to the `libmagma.so` file in `skcuda/magma.py` by modifying [this](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/magma.py#L18) line.

**Comment by hnykda** [comment]
I actually tried that:

```
$ echo $LD_LIBRARY_PATH
:/usr/local/cuda/lib64:/home/hnykdan1/vu/magma/lib

$ ls -la /home/hnykdan1/vu/magma/lib/libmagma.a
-rw-rw-r-- 1 hnykdan1 hnykdan1 51M pro 20 16:33
/home/hnykdan1/vu/magma/lib/libmagma.a
```

and when I tried to hardcode it:
```
libmagma_libname_list = ['/home/hnykdan1/vu/magma/lib/libmagma.a']
```

In both cases, I am getting:
```
$ python demo_magma.py
Traceback (most recent call last):
  File "demo_magma.py", line 8, in <module>
    import skcuda.magma as magma
  File "/home/hnykdan1/vu/skcuda/scikit-cuda/skcuda/magma.py", line 36, in
<module>
    raise OSError('%s not found' % _load_err)
OSError: libmagma.a not found
```


út 20. 12. 2016 v 23:06 odesílatel Lev E. Givon <notifications@github.com>
napsal:

**Comment by hnykda** [comment]
I actually tried that:

```
$ echo $LD_LIBRARY_PATH
:/usr/local/cuda/lib64:/home/hnykdan1/vu/magma/lib

$ ls -la /home/hnykdan1/vu/magma/lib/libmagma.a
-rw-rw-r-- 1 hnykdan1 hnykdan1 51M pro 20 16:33
/home/hnykdan1/vu/magma/lib/libmagma.a
```

and when I tried to hardcode it:
```
libmagma_libname_list = ['/home/hnykdan1/vu/magma/lib/libmagma.a']
```

In both cases, I am getting:
```
$ python demo_magma.py
Traceback (most recent call last):
  File "demo_magma.py", line 8, in <module>
    import skcuda.magma as magma
  File "/home/hnykdan1/vu/skcuda/scikit-cuda/skcuda/magma.py", line 36, in
<module>
    raise OSError('%s not found' % _load_err)
OSError: libmagma.a not found
```

**Comment by lebedov** [comment]
`libmagma.a` is a static library - you need to build MAGMA as a shared library in order to use it from Python.

**Comment by hnykda** [comment]
Thanks for helping. I managed to compile that beast, but still getting the same:

```
$ python demo_magma.py                                     
Traceback (most recent call last):
  File "demo_magma.py", line 8, in <module>
    import skcuda.magma as magma
  File "/home/hnykdan1/vu/skcuda/scikit-cuda/skcuda/magma.py", line 907, in <module>
    _libmagma.magma_get_ssygst_nb_m.restype = int
  File "/home/hnykdan1/.miniconda/envs/vu/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/home/hnykdan1/.miniconda/envs/vu/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/hnykdan1/vu/magma/lib/libmagma.so: undefined symbol: magma_get_ssygst_nb_m

# but it seems to be correct
$ ldd /home/hnykdan1/vu/magma/lib/libmagma.so 
        linux-vdso.so.1 =>  (0x00007fff45400000)
        libcudart.so.7.0 => /usr/local/cuda/lib64/libcudart.so.7.0 (0x00007f0ba2438000)
        libcublas.so.7.0 => /usr/local/cuda/lib64/libcublas.so.7.0 (0x00007f0ba0470000)
        libcusparse.so.7.0 => /usr/local/cuda/lib64/libcusparse.so.7.0 (0x00007f0b9d8e8000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f0b9d120000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f0b9cea0000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0b9cb98000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0b9c890000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0b9c678000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0b9c2b0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0b9c0a8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0b9be88000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0b9bc80000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f0b9b960000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0ba5568000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f0b9b720000)

$ echo $LD_LIBRARY_PATH 
:/usr/local/cuda/lib64:/home/hnykdan1/vu/magma/lib
```

**Comment by lebedov** [comment]
Which version of MAGMA are you using? Some of the symbol names may
have changed; if so, I'll have to update the wrappers.

**Comment by hnykda** [comment]
I am using magma 2.2.0 build from source. Which version should I use?

**Comment by lebedov** [comment]
I was using 2.1.0, but MAGMA 2.2.0 still seems to have the requisite
symbols in it. Will try it out.

**Comment by hnykda** [comment]
OK. Thanks

**Comment by gul916** [comment]
@lebedov 
Hello,
I have similar difficulties to initialize magma :
```python
import skcuda.magma as magma
Traceback (most recent call last):

  File "<ipython-input-17-a9c5c2e853b0>", line 1, in <module>
    import skcuda.magma as magma

  File "/opt/anaconda3/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/magma.py", line 36, in <module>
    raise OSError('%s not found' % _load_err)

OSError: libmagma.so not found
```

Everything seems correct in bash:
```bash
$ ldconfig -v | grep magma
/usr/local/magma/lib:
	libmagma_sparse.so -> libmagma_sparse.so
	libmagma.so -> libmagma.so
$ ls /usr/local/magma/lib
libmagma.a  libmagma.so  libmagma_sparse.a  libmagma_sparse.so  pkgconfig
$ ldd /usr/local/magma/lib/libmagma.so | grep "not found"
```
I am using magma 2.2.0 compiled with mkl 2017.4 and cuda 8.0 under Linux Fedora 25.
Thanks for your help

**Comment by lebedov** [comment]
Are the magma shared libs world readable/executable? I haven't encountered any problems with either py2 or py3 and magma 2.2.0 locally installed in a conda environment.

**Comment by gul916** [comment]
Hi,
Yes they are:
```
$ ls -l /usr/local/magma/lib
total 322332
-rw-r--r--. 1 root root 110174900 24 août  14:30 libmagma.a
-rwxr-xr-x. 1 root root 105307192 24 août  14:30 libmagma.so
-rw-r--r--. 1 root root  58656552 24 août  14:30 libmagma_sparse.a
-rwxr-xr-x. 1 root root  55909952 24 août  14:30 libmagma_sparse.so
drwxr-xr-x. 2 root root      4096 24 août  14:30 pkgconfig
$
$ ldd /usr/local/magma/lib/libmagma.so
	linux-vdso.so.1 (0x00007ffe72b31000)
	libmkl_gf_lp64.so => /opt/intel/mkl/lib/intel64_lin/libmkl_gf_lp64.so (0x00007fc714ade000)
	libmkl_gnu_thread.so => /opt/intel/mkl/lib/intel64_lin/libmkl_gnu_thread.so (0x00007fc713896000)
	libmkl_core.so => /opt/intel/mkl/lib/intel64_lin/libmkl_core.so (0x00007fc711d64000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc711b46000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc7117be000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fc71148d000)
	libcublas.so.8.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.8.0 (0x00007fc70e448000)
	libcusparse.so.8.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcusparse.so.8.0 (0x00007fc70b92d000)
	libcudart.so.8.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.8.0 (0x00007fc70b6c7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc70b3be000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc70b190000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc70af79000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc70abb3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc70a9af000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc71bad8000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fc70a76f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc70a567000)
```
Here is how I installed MKL:
```
# dnf config-manager --add-repo https://yum.repos.intel.com/setup/intelproducts.repo
# rpm --import https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
# dnf install intel-mkl-2017.3-056.x86_64
# echo "/opt/intel/mkl/lib/intel64_lin" > /etc/ld.so.conf.d/mkl.conf
# ldconfig -v | grep mkl
```
And how I installed magma:
```
# dnf install gcc-gfortran
$ cd ~/Téléchargements/Magma/magma-2.2.0
$ cp make.inc-examples/make.inc.mkl-gcc make.inc
$ vi make.inc --> GPU_TARGET ?= Fermi Kepler Maxwell Pascal
$ source /opt/intel/mkl/bin/mklvars.sh intel64
$ export CUDADIR=/usr/local/cuda
$ make -j 12 shared
$ make -j 12 tests
# make -j 12 install prefix=/usr/local/magma
# echo "/usr/local/magma/lib/" > /etc/ld.so.conf.d/magma.conf
# ldconfig -v | grep magma
```
Is there any additional step I need to do ?

**Comment by lebedov** [comment]
Strange - the steps you indicated look fine. Out of curiosity, does adding /usr/local/magma/lib to LD_LIBRARY_PATH make any difference (not sure why it would given that you configured ld.so, but it couldn't hurt to try)?

**Comment by gul916** [comment]
No, it doesn't change anything:
```
$ LD_LIBRARY_PATH=/usr/local/magma/lib python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

import skcuda.magma as magma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/magma.py", line 36, in <module>
    raise OSError('%s not found' % _load_err)
OSError: libmagma.so not found
```
Could it be due to a difference between 32 and 64 bits libraries ? Or to the way skcuda has been installed ? Here it was using
```
conda install -c lukepfister scikits.cuda
conda update libgcc numpy
```

**Comment by lebedov** [comment]
The magma shared library and the version of Python you are using must both be compiled for the same architecture (32 or 64 bit).

Try installing the latest scikit-cuda code on GitHub - the version in the `lukepfister` conda channel might not be up to date.

**Comment by gul916** [comment]
Hi @lebedov 
Sorry for the delay.

It doesn't change anything when using scikit-cuda from master branch
```bash
$ conda remove scikits.cuda
$ cd scikit-cuda-master/
$ python setup.py install
$ cd && python
```
```python
import skcuda.magma as magma

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/opt/anaconda3/lib/python3.6/site-packages/scikit_cuda-0.5.2-py3.6.egg/skcuda/magma.py", line 36, in <module>
raise OSError('%s not found' % _load_err)
OSError: libmagma.so not found
```
Cheers

**Comment by lebedov** [comment]
Feel free to reopen if this is still an issue.
