### ISSUE TITLE
Error on cusolver import

### ISSUE THREAD

**Issue by mharradon** [lebedov/scikit-cuda#196]
I'm seeing this error on import with cuda7.5:

```
>>>import skcuda
>>>from skcuda import cusolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harradon/MyCode/scikit-cuda/skcuda/cusolver.py", line 1137, in <module>
    _libcusolver.cusolverDnSsyevd_bufferSize.restype = int
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/cuda/lib64/libcusolver.so: undefined symbol: cusolverDnSsyevd_bufferSize
```

Thanks for any suggestions!

**Comment by mharradon** [comment]
Solved on update to cuda8!
