### ISSUE TITLE
Can't install latest scikit-cuda

### ISSUE THREAD

**Issue by StefanoD** [lebedov/scikit-cuda#200]
```
(keras-stefano-env) stefano@stefano-linux:~/Dokumente/Programming/Python$ pip3 install -U git+https://github.com/lebedov/scikit-cuda.git#egg=scikit-cuda
Collecting scikit-cuda from git+https://github.com/lebedov/scikit-cuda.git#egg=scikit-cuda
  Cloning https://github.com/lebedov/scikit-cuda.git to /tmp/pip-build-bfdailzo/scikit-cuda
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/stefano/Dokumente/Programming/Python/keras-stefano-env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bfdailzo/scikit-cuda/
```

**Comment by lebedov** [comment]
I can't replicate this error when I run the specified installation command (replacing pip3 with pip) in a Python 3.5 conda environment on Ubuntu 16.04. Can you try updating setuptools/pip in your conda repo?

**Comment by StefanoD** [comment]
I'm using Ubuntu 16.04, too.
```
(keras-stefano-env) stefano@stefano-linux:~/Dokumente/Programming/Python$ pip3 install -U setuptools
Requirement already up-to-date: setuptools in ./keras-stefano-env/lib/python3.5/site-packages
Requirement already up-to-date: six>=1.6.0 in ./keras-stefano-env/lib/python3.5/site-packages (from setuptools)
Requirement already up-to-date: appdirs>=1.4.0 in ./keras-stefano-env/lib/python3.5/site-packages (from setuptools)
Requirement already up-to-date: packaging>=16.8 in ./keras-stefano-env/lib/python3.5/site-packages (from setuptools)
Requirement already up-to-date: pyparsing in ./keras-stefano-env/lib/python3.5/site-packages (from packaging>=16.8->setuptools)
```
```
(keras-stefano-env) stefano@stefano-linux:~/Dokumente/Programming/Python$ pip3 install -U pip
Requirement already up-to-date: pip in ./keras-stefano-env/lib/python3.5/site-packages
```

**Comment by StefanoD** [comment]
Did you try to reproduce this in an virtual environment?

**Comment by lebedov** [comment]
Yes - I tried it both in a conda (4.3.18) environment and a virtualenv (15.1.0) environment. The environment has setuptools 35.0.2 and pip 9.0.1 installed.

**Comment by lebedov** [comment]
Still can't reproduce with Python 3.6. Please reopen if still a problem.
