### ISSUE TITLE
Error on cusolver import

### ISSUE THREAD

**Issue by chenzhi2223** [lebedov/scikit-cuda#201]

**Comment by chenzhi2223** [comment]
when I import cusolver, I got the following error.
Traceback (most recent call last):
  File "cusolver_demo_svd.py", line 10, in <module>
    import skcuda.cusolver as solver
  File "/home/z335chen/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cusolver.py", line 1137, in <module>
    _libcusolver.cusolverDnSsyevd_bufferSize.restype = int
  File "/opt/sharcnet/python/2.7.8/gcc/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/opt/sharcnet/python/2.7.8/gcc/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /opt/sharcnet/cuda/7.5.18/lib64/libcusolver.so: undefined symbol: cusolverDnSsyevd_bufferSize

Since I am using the cluster I have to stick to cuda version. 7.5.
Helpful suggestions is greatly appreciated.

**Comment by lebedov** [comment]
I added some additional library version checking to skcuda.cusolver to disable functions for cusolver >= 8.0 if an earlier version is present. Let me know if this solves the import problem.

**Comment by chenzhi2223** [comment]
Dear Levedov,

         Thanks a lot for your efforts. Actually I installed an earlier
version (0.5.0), which worked out. Please let other know if them ask the
same questions.

        Truly appreciate your help and prompt reply.

        Yours sincerely,

        Zhi Chen

2017-05-24 23:54 GMT-04:00 Lev E. Givon <notifications@github.com>:
