### ISSUE TITLE
The cublasError

### ISSUE THREAD

**Issue by KrisCheng** [lebedov/scikit-cuda#221]
I am running the theano GPU version on a server, buy there exists an error said that:
"line 177, in cublasCheckStatus
raise cublasError
skcuda.cublas.cublasError"
there is no explanation on the source code. I want to know the reason and fix my problem. urgently!!!

**Comment by nmerrill67** [comment]
Have you tried rebooting? That is a common error with nvidia drivers when a machine has been suspended.

**Comment by KrisCheng** [comment]
Yes, I tried many times, but every time the machine occurs this same error. and I have no idea for that.

**Comment by lebedov** [comment]
Can you run the skcuda unit tests on your machine successfully? Also, can you post the full error trace? I can't diagnose the problem without further information.

**Comment by KrisCheng** [comment]
Here is the detailed log:

WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (libmkl_rt.so: cannot open shared object file: No such file or directory)
objdump: '/BIGDATA/app/CUDA/8.0/lib64/stubs/libcublas.so.8.0': No such file
/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cublas.py:282: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')

You are running using the stub version of libcublas
.Traceback (most recent call last):
  File "hko_sequence_forecasting.py", line 3, in <module>
    import theano
  File "/BIGDATA/app/Python/2.7.9/lib/python2.7/site-packages/Theano-0.10.0.dev1-py2.7.egg/theano/__init__.py", line 134, in <module>
    import theano.gpuarray
  File "/BIGDATA/app/Python/2.7.9/lib/python2.7/site-packages/Theano-0.10.0.dev1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, extra_ops, multinomial, reduction, rng_mrg
  File "/BIGDATA/app/Python/2.7.9/lib/python2.7/site-packages/Theano-0.10.0.dev1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/BIGDATA/app/Python/2.7.9/lib/python2.7/site-packages/Theano-0.10.0.dev1-py2.7.egg/theano/gpuarray/opt.py", line 76, in <module>
    from .linalg import (GpuCusolverSolve, MATRIX_STRUCTURES_SOLVE, GpuCholesky,
  File "/BIGDATA/app/Python/2.7.9/lib/python2.7/site-packages/Theano-0.10.0.dev1-py2.7.egg/theano/gpuarray/linalg.py", line 29, in <module>
    from skcuda import cusolver
  File "/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cusolver.py", line 22, in <module>
    from . import cublas
  File "/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cublas.py", line 290, in <module>
    _cublas_version = int(_get_cublas_version())
  File "/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cublas.py", line 283, in _get_cublas_version
    h = cublasCreate()
  File "/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cublas.py", line 201, in cublasCreate
    cublasCheckStatus(status)
  File "/HOME/iocas_mmu_6/.local/lib/python2.7/site-packages/scikit_cuda-0.5.2-py2.7.egg/skcuda/cublas.py", line 177, in cublasCheckStatus
    raise cublasError
skcuda.cublas.cublasError

Thank you! this trouble me for several days!

**Comment by lebedov** [comment]
Where is CUDA installed on your system? Can you run other programs/packages that use CUDA (e.g., pycuda) without error?

**Comment by elmines** [comment]
I am having a comparable issue. In utils.py, the regular expression used to find a libcublas.so file returns a file path that does not exist. It will create the path /opt/asn/apps/cuda_8.0.44/lib64/stubs/libcublas.so.8.0, but the contents of /opt/asn/apps/cuda_8.0.44/lib64/ are as follows:

**libcublas.so** libcuda.so libcufft.so libcufftw.so libcurand.so libcusolver.so libcusparse.so libnppc.so libnppial.so libnppicc.so libnppicom.so libnppidei.so libnppif.so libnppig.so libnppim.so libnppi.so libnppist.so libnppisu.so libnppitc.so libnpps.so libnvgraph.so libnvidia-ml.so libnvrtc.so

As can be seen, the stub file is available, but I believe find_lib_path() in utils.py is generating an incorrect path.

**Comment by lebedov** [comment]
@KrisCheng, please reopen if this is still an issue. @elmines, please open a separate issue if you are still encountering problems - it's preferable to open a new issue and reference existing issues in it rather than append to an existing one before we verify that the issues are actually  the same.
