### ISSUE TITLE
cublasZgetriBatched causes segfault in GPU, while cublasDgetriBatched doesn't

### ISSUE THREAD

**Issue by sgranade** [lebedov/scikit-cuda#261]
## Problem

I've been successfully using `cublasDgetriBatched()` in my code, but I'm now handling complex data and seeing GPU segfaults with `cublasZgetriBatched()`.

```python
import numpy as np
from pycuda import gpuarray
import pycuda.autoinit
import skcuda.cublas as cublas


def example_cublasDgetriBatched(handle):
    a = np.array([[[1, 1], [1, 0.1]]]).astype(np.float64)
    m, n, _ = a.shape
    a_dev = gpuarray.empty(a.shape, dtype=a.dtype, order='F')
    a_ptrs = gpuarray.arange(a_dev.ptr, a_dev.ptr + a_dev.shape[0] * a_dev.strides[0], a_dev.strides[0],
                             dtype=cublas.ctypes.c_void_p)
    ipiv = gpuarray.empty((m, n), dtype=np.int32)
    info_array = gpuarray.zeros(m, dtype=np.int32)
    c_dev = gpuarray.empty(a.shape, dtype=a.dtype, order='F')
    c_ptrs = gpuarray.arange(c_dev.ptr, c_dev.ptr + c_dev.shape[0] * c_dev.strides[0], c_dev.strides[0],
                             dtype=cublas.ctypes.c_void_p)

    a_dev.set(a)
    cublas.cublasDgetrfBatched(handle, n, a_ptrs.gpudata, n, ipiv.gpudata, info_array.gpudata, m)
    cublas.cublasDgetriBatched(handle, n, a_ptrs.gpudata, n, ipiv.gpudata, c_ptrs.gpudata, n,
                               info_array.gpudata, m)
    c = c_dev.get()
    return c


def example_cublasZgetriBatched(handle):
    a = np.array([[[1+2j, 1], [1, 0.1]]]).astype(np.complex128)
    m, n, _ = a.shape
    a_dev = gpuarray.empty(a.shape, dtype=a.dtype, order='F')
    a_ptrs = gpuarray.arange(a_dev.ptr, a_dev.ptr+a_dev.shape[0]*a_dev.strides[0],
        a_dev.strides[0], dtype=cublas.ctypes.c_void_p)
    ipiv = gpuarray.empty((m, n), dtype=np.int32)
    info_array = gpuarray.zeros(m, dtype=np.int32)
    c_dev = gpuarray.empty(a.shape, dtype=a.dtype, order='F')
    c_ptrs = gpuarray.arange(c_dev.ptr, c_dev.ptr+c_dev.shape[0]*c_dev.strides[0],
        c_dev.strides[0], dtype=cublas.ctypes.c_void_p)

    a_dev.set(a)
    cublas.cublasZgetrfBatched(handle, n, a_ptrs.gpudata, n, ipiv.gpudata, info_array.gpudata, m)
    cublas.cublasZgetriBatched(handle, n, a_ptrs.gpudata, n, ipiv.gpudata, c_ptrs.gpudata, n,
                               info_array.gpudata, m)
    c = c_dev.get()
    return c


handle = cublas.cublasCreate()
c_float = example_cublasDgetriBatched(handle)
c_complex = example_cublasZgetriBatched(handle)
```

The call to `example_cublasDgetriBatched()` works fine, while the call to `example_cublasZgetriBatched()` fails:

```
Traceback (most recent call last):
  File "scratch.py", line 51, in <module>
    c_complex = example_cublasZgetriBatched(handle)
  File "scratch.py", line 45, in example_cublasZgetriBatched
    c = c_dev.get()
  File "/usr/local/lib/python3.5/dist-packages/pycuda/gpuarray.py", line 271, in get
    _memcpy_discontig(ary, self, async=async, stream=stream)
  File "/usr/local/lib/python3.5/dist-packages/pycuda/gpuarray.py", line 1248, in _memcpy_discontig
    drv.memcpy_dtoh(dst, src.gpudata)
pycuda._driver.LaunchError: cuMemcpyDtoH failed: unspecified launch failure
```

While chasing this down, I also discovered that, while `cublas<t>getrfBatched()` is covered in the unit tests, `cublas<t>getriBatched()` isn't.

## Environment
* Ubuntu 16.04
* Python 3.5
* CUDA 9.0, installed via Jetpack on a Jetson TX2
* PyCUDA 2017.1.1, installed via pip
* scikit-cuda 0.5.2 (GitHub revision f6cc36cf81aa16dbe47a8e8d880db9e17517d788)

**Comment by sgranade** [comment]
I figured it out: cublasZgetriBatched() and cublasCgetriBatched() don't have their restypes or argtypes set, causing the error.

**Comment by lebedov** [comment]
Fixed - thanks.
