### ISSUE TITLE
scikit-cuda test failed

### ISSUE THREAD

**Issue by beew** [lebedov/scikit-cuda#299]
Compiled scikit-cuda from source, build no problem but one test failed

The output for 

python setup.py test

```
Ran 336 tests in 56.388s

OK (skipped=61)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/pycuda-2019.1.2-py3.8-linux-x86_64.egg/pycuda/tools.py", line 34, in <module>
    import pycuda.driver as cuda
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/pycuda-2019.1.2-py3.8-linux-x86_64.egg/pycuda/driver.py", line 8, in <module>
    import numpy as np
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/numpy/core/overrides.py", line 16, in <module>
    add_docstring(
RuntimeError: implement_array_function method already has a docstring
```

* OS platform : Ubuntu linux 
* Python version: 3.8.3
* CUDA version: 10.0 from Nvidia and linked to /usr/local/cuda
* scikit-cuda version 0.5.3

In addition
pycuda 2019.1.2
numpy 1.18.4

**Comment by lebedov** [comment]
The error is not coming from a failed skcuda test because "OK" was printed after the tests were all run and the traceback doesn't come directly from a test. I can't replicate the problem with those package versions and Python 3.8.2; can you please try an earlier version of numpy?

**Comment by beew** [comment]
Tried numpy 1.17.5 on scikit-cuda 0.5.3, pycuda from git and python-3.8.5 still same test error (which probably is harmless)

With  sciki-cuda master there is one additional test error
```
Failure: OSError (libmagma.so not found)

```

I think you need a pay subscription to get libmagma.so from MAGMA.

**Comment by lebedov** [comment]
There [might be a fix for this issue](https://github.com/numpy/numpy/issues/14384) in numpy 1.19+ - try that and see what happens.
 
Magma is free software - you don't need to pay any subscription to obtain it. I actually built a [conda package](https://anaconda.org/lebedov/magma/files) for it once that contains the shared library, although it probably ought to be updated to the latest version.

**Comment by beew** [comment]
@lebedov 

`Magma is free software`

Really??!! From SAGE's manifesto 'Mission: Creating a viable free open source alternative to Magma, Maple, Mathematica and Matlab' https://www.sagemath.org/

So I take that to mean Magma is not free, rather like Maple, Mathematica and Matlab.

**Comment by grlee77** [comment]
>Really??!! From SAGE's manifesto 'Mission: Creating a viable free open source alternative to Magma, Maple, Mathematica and Matlab' https://www.sagemath.org/

> So I take that to mean Magma is not free, rather like Maple, Mathematica and Matlab.

The MAGMA used by scikit-cuda is [this one](http://icl.cs.utk.edu/magma/software/). The software that SAGE manifesto is referring to is a [different MAGMA](http://magma.maths.usyd.edu.au/magma/) for computer algebra.

**Comment by vincefn** [comment]
The reported error is not present anymore in numpy 1.19 (see https://github.com/numpy/numpy/issues/14384), so this can probably be closed.
(Note that I did not reproduce this in scikit-cuda, but in another package I had the same issue when exiting the test, and this was fixed upgrading to numpy 1.19)
