### ISSUE TITLE
OSError: cusolver library not found

### ISSUE THREAD

**Issue by MxQuantFinance** [lebedov/scikit-cuda#307]
Good day!
Studied similar issues, verified paths, commands, ctypes etc. 
pycuda examples etc work.
But still can't get ir working.

## Problem
Error message:
C:\Users\user\Anaconda3\lib\site-packages\scikit_cuda-0.5.4-py3.7.egg\skcuda\cublas.py:289: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
Traceback (most recent call last):
  File "G:\SVD_PCA\SVD\SVD.py", line 5, in <module>
    from skcuda import linalg
  File "C:\Users\user\Anaconda3\lib\site-packages\scikit_cuda-0.5.4-py3.7.egg\skcuda\linalg.py", line 26, in <module>
    from . import cusolver
  File "C:\Users\user\Anaconda3\lib\site-packages\scikit_cuda-0.5.4-py3.7.egg\skcuda\cusolver.py", line 65, in <module>
    raise OSError('cusolver library not found')

## Environment

* OS platform: Windows 10 Enterpise 1903
* Python version: 3.7 (Anaconda x64)
* CUDA version: 11.1 installed through .exe cuda toolkit setup
* PyCUDA version 2020.1 from GitHub
* scikit-cuda version: 0.5.4 from GitHub (tried also using pip install )

**Comment by MxQuantFinance** [comment]
Funny but
libcusolver file name: cusolver64_70.dll

So i renamed cusolver64_11.dll to cusolver64_70.dll and 

`from skcuda import linalg` passed without error

Good question: why 64_70?


Very good news: cusolver_demo_svd.py fired.

Everything was done in Visual Studio 2019
